### ISSUE TITLE
Associations, reverse associations and autoFetching

### ISSUE THREAD

**Issue by axedre** [dresende/node-orm2#118]
Hey everyone.
Ok fisrt of all I'm sorry if I come back on this subject, but it's really riddling me to the point of frustration.
I'm still having a hard time making reverse associations work. This is my code:

```
module.exports = function(db) {
    this.User = db.define("user", {
        //...
    }, {
        autoFetch: true
    });

    this.Team = db.define("team", {
        //...
    }, {
        autoFetch: true,
        methods: {
            //...
        }
    });

    this.Player = db.define("player", {
        //...
    }, {
        autoFetch: true,
        methods: {
            //...
        }
    });

    this.User.hasOne("team", this.Team);
    this.Player.hasOne("team", this.Team, {
       reverse: "players"
    });
}
```

My express server has the following API calls:

```
app.get("/api/me", function(req, res) {
    //req.user stores an authenticated user, which is fetched with the
    //Model.find() method
    return res.send(req.user);
});
app.get("/api/player/:id", function(req, res) {
    model.Player.get(req.params.id, function(err, player) {
        res.send(player);
    });
});
app.get("/api/me/team", function(req, res) {
    model.Team.get(req.user.team.id, function(err, team) {
        res.send(team);
    });
});
```

What I see client-side upon invoking those API calls:

```
$http.get("/api/me").success(function(user) {
    console.log(user);
});
$http.get("/api/player/1").success(function(player) {
    console.log(player);
});
$http.get("/api/me/team").success(function(team) {
    console.log(team);
});
```

The first `console.log` correctly outputs a user object without the _team_id_ property, which is conveniently (and expectedly) replaced by a _team_ property which is an object containing the user's team **BUT** the team does not in turn have a _players_ property containing all that team's players (as I expected from the reverse association + the `autoFetch` option on the `Team` model.

The second `console.log` correctly outputs all the player's properties, but _team_id_ is not replaced by the _Team_ object, as expected.

As in the first `console.log`, the last on correctly outputs all the team's properties, but there is still no _players_ property containing an array of players.
I am utterly stumbled. I can provide all further information if you wish to reproduce the error.
Thanks in advance.

Andy

**Comment by dawadam** [comment]
Hi, is it solved ?
