### ISSUE TITLE
sql error occurs when update orm to 2.0.9

### ISSUE THREAD

**Issue by huangyingjie** [dresende/node-orm2#132]
Hi Diogo,
     When I update orm to 2.0.9, some query failured and the error log is below:

``` js
{ [Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'] code: 'ER_BAD_FIELD_ERROR', index: 0 }
```

   Does the sql-query@0.0.19 force that any table must be created with an column id?
   My table has no id. When I add column id, the error dispeared, however all the data are the same one no matter how many rows I select.

``` js
        Person.find({age: 60}, ["country", "A"], function (err, page) {
            console.log(err);
        });
```

**Comment by apmeena** [comment]
How can i change primary key name "id" to any other name like "userId"?
