### ISSUE TITLE
Can I use a uuid as the primarykey?

### ISSUE THREAD

**Issue by veilevil** [dresende/node-orm2#139]
Guys
Is there anyway to use a uuid as the primaykey?

**Comment by omarfouad** [comment]
Not sure if this is right but I'm using the uuid module to set the value of the id: 

```js
var uuid = require('uuid');
```

Then I set the id in the model this way:
```js
id: {type: 'text', required: true, defaultValue: uuid.v4(), unique: true, key: true}
```

This way, whenever I create a new record, without explicitly assigning a value to the id, it will default to a generated uuid. Somehow though, it doesn't save.

**Comment by omarfouad** [comment]
Any idea everyone?

**Comment by adi** [comment]
@omarfouad defaultValue sets the ID column's default to the one UUID generated when uuid.v4() was called. It doesn't call uuid.v4() for every object.
