### ISSUE TITLE
How to create tables?

### ISSUE THREAD

**Issue by callumlocke** [dresende/node-orm2#21]
Sorry if this is a stupid question, but: How do you create tables with node-orm2?

The original node-orm wiki mentions the [`.sync()`](https://github.com/dresende/node-orm/wiki/Defining-models) method for models, which would create all the necessary tables...

But this method doesn't seem to exist in node-orm2. Am I supposed to create my tables manually? If so, I need some more information, like what kind of naming convention node-orm2 expects for association tables and foreign key field names, etc. (Or does this documentation already exist somewhere?)

**Comment by phikal** [comment]
Has anything changed with sqlite until now?

**Comment by jsammarco** [comment]
This doesn't see to do anything for me for mySQL, .sync() is there and I get no errors but it doesn't create tables or add columns.
