### ISSUE TITLE
Unique together

### ISSUE THREAD

**Issue by colegleason** [dresende/node-orm2#288]
It would be nice to specify that two or more columns have to be unique together, but not unique themselves.

**Comment by anlebcoder** [comment]
> I'm not sure about how parsable the errors would be, but I don't think we necessarily have to wrap them in anything special. Ideally the user shouldn't be running queries which violate the DB schema in the first place.
> 
> Maybe we can have both the validator and the `unique` property and allow them to fulfil different tasks. The validator can act as a stopgap between bad input into the user's application and the database queries, while the `unique` property can act as a database schema restriction. I think given the way the two would be used that it makes sense to do it that way, and the user would expect schema errors to be returned by the database engine post query.
> 
> Essentially we could have the following
> 
> ```js
> db.define('model', {
>     id: { type: 'text', required: true, unique: true },
>     first_name: { type: 'text', required: true, unique: 'name' },
>     last_name: { type: 'text', required: true, unique: 'name' },
>     email: { type: 'text', unique: true }
> }, {
>     id: 'id',
>     validations: {
>         first_name: [orm.enforce.required(), orm.enforce.unique('name')],
>         last_name: [orm.enforce.required(), orm.enforce.unique('name')],
>         email: [orm.enforce.patterns.email(), orm.enforce.unique().orUndefined()]
>     }    
> });
> ```
> 
> It should then generate the following MySQL table creation query, using the model name and `unique` key if present, or the name of the field if `unique = true` to generate the index name.
> 
> ```sql
> CREATE TABLE model (
>     id VARCHAR(255) NOT NULL, 
>     first_name VARCHAR(255) NOT NULL, 
>     last_name VARCHAR(255) NOT NULL,
>     email VARCHAR(255),
>     PRIMARY KEY(id),
>     UNIQUE INDEX IX_model_name (first_name, last_name),
>     UNIQUE INDEX IX_model_email (email)
>     );
> ```
> 
> We can then keep the enforce validator for `unique` and allow that to do pre-query validation on the fields if the user wishes.
> 
> How does that sound to you guys?

good job.


index together:  set `index` same value ,like this: 'id_name_index';

unique together:  set `unique` same value ,like this: 'id_name_unique';
