### ISSUE TITLE
Error: Connection lost - driver does not support reconnection

### ISSUE THREAD

**Issue by grahamreeds** [dresende/node-orm2#289]
I am trying to use SQLite as the backend to a simple app but get the above message whenever I try anything more than a toy app. For instance this works:

``` javascript
var orm = require("orm");
var people = [];

orm.connect('sqlite://test.s3db', function (err, db) {
    if (err) throw err;

    var Phone = db.define("Phone", {
        person_id : Number,
        number    : String
    },{});

    var Person = db.define("Person", {
        id        : Number,
        name      : String
    },{});

    Person.find({}, function (err, people) {
        console.log("People found: %d", people.length);
        console.log("First person: %s", people[0].name);
    });
});
```

However a more complex app gets the Connect lost message.  I am using Express but not the orm.express method because it doesn't work with the way I want to layout my application.  In my app I do this:

``` javascript
orm.connect('sqlite://sqlite.s3db', function(err,db){
    !err && console.log("db connected!");
    if (err){
        throw err;
    }
    db.load('./models', function(err){
        app.Phone = db.models.Phone;
        app.Person = db.models.Person ;
        !err && console.log("models loaded!");
    });

    // link models to routes
    app.get('/', routes.users(app.Phone, app.Person));
});
```

Any ideas as to why I am losing the connection and is my way of doing things the 'correct' way.  I am not a javascript programmer in any way, shape or form.

**Comment by zuoyoufei** [comment]
Same problem occured in my project, however I don't konw whether the dependency I was running is correct. Sometimes it works while sometimes not. So ,could you please tell me the dependecy of your project?
