### ISSUE TITLE
Cache Clear Documentation

### ISSUE THREAD

**Issue by toddpi314** [dresende/node-orm2#564]
For many use cases, the ORM module cache needs to be manually cleared.
This is useful in cases where you are bootstrapping mocha tests and need isolation, or are pooling resources on a server.

This can be done by calling orm.singleton.clear().

Can someone update the documentation to reflect this?

**Comment by lvanbuiten** [comment]
It saved me some headache! I don't know why they don't refresh the cache when a model has changed. When i have a 'list' with 'items' and create a new 'item', the list doesn't retrieve the new item on page refresh, it does on server restart...

**Comment by dxg** [comment]
The cache is not a cache, but an identity pattern implementation. I hope to disable it by default and rename accordingly in a future release.
