### ISSUE TITLE
Calculate additional column and sort by it

### ISSUE THREAD

**Issue by devoll** [dresende/node-orm2#601]
How I can add additional calculated column and sort by it? Example SQL:

```SQL
SELECT amount, fee, (amount - fee) as profit 
FROM payments 
WHERE client_id = 10 
ORDER BY profit 
DESC LIMIT 20, 10
```

Thank you!

**Comment by johanroyen** [comment]
You could do a [raw query](https://github.com/dresende/node-orm2#raw-queries).
