### ISSUE TITLE
orm update has cache

### ISSUE THREAD

**Issue by lonso** [dresende/node-orm2#626]
when i update model, i change data on mysql command line.
But i orm2,the data not change need i use 
`
orm.singleton.clear();
`
that data will be change.
why?

**Comment by newradius** [comment]
I had the same problem and I lost like 2 hours so I disabled the cache globally.
db.settings.set('instance.cache', false);

**Comment by dxg** [comment]
The cache isn't really a cache, but a singleton pattern.
Did you update it via ORM calls or SQL?

I too disabled it globally.

**Comment by newradius** [comment]
I update via ORM calls.

**Comment by dxg** [comment]
Can you provide a limited code sample? Like the one [here](https://github.com/dresende/node-orm2/issues/622).

**Comment by newradius** [comment]
If i try to update the same object, it only updates 1 time. Let's say I want to update an UserRole I retrieve the user with .get and update it but if I want to update it againt the UserRole doesn't update the 2nd time.

**Comment by dxg** [comment]
If you provide a code sample or even better, a failing test case, then I may be able to do something with it.

**Comment by Sebush** [comment]
cache and cluster... how can i purge the "cache" in cluster-express-configuration? my solution at the moment is to disable orm-cache

**Comment by dxg** [comment]
Orm cache isn't a cache at all, but an identity map. I don't see anything wrong with disabling it.
