### ISSUE TITLE
orm2 can support table alias?

### ISSUE THREAD

**Issue by qiangzi109901** [dresende/node-orm2#651]
now, mysql has a table named 'qz_blog'
<pre><code>
//normal defined
var Blog = db.define('qz_blog', {
    id 			: Number,
    title       : String,
    content     : String,
    type        : Number, 
    create_time : Date,
    abstract    : String
  },
</code></pre>
but I want define this model named 'blog',just like this
<pre><code>
//define demo
var Blog = db.define('blog', {
    id 			: Number,
    title       : String,
    content     : String,
    type        : Number, 
    create_time : Date,
    abstract    : String
  },
</code></pre>

<pre><code>
//use  demo
req.models.blog.get(425,function(err,blog){
	if(err) throw err;
	res.render('index',{
		title : '首页',
		blog : blog
	});
});
</code></pre>

**Comment by dxg** [comment]
Try:
```js
var Blog = db.define('blog', {
    id          : Number,
    title       : String,
    content     : String,
    type        : Number, 
    create_time : Date,
    abstract    : String
  },
  {
    collection: "qz_blog"
  }
```
From [lib/ORM.js#L230](https://github.com/dresende/node-orm2/blob/v2.1.26/lib/ORM.js#L230)

**Comment by qiangzi109901** [comment]
### ok，thank you for your suggestion
