### ISSUE TITLE
Can orm2 create a table automatically?

### ISSUE THREAD

**Issue by hacke2** [dresende/node-orm2#659]
I use Hibernate in J2ee, when the datebase has't table the framework can create table and when fields changed it can update datebase,  Can this be done?

**Comment by dxg** [comment]
It can manually create tables by calling `.sync` but does not do this automatically.
It had some initial work done on updating fields, but this functionality was never completed and is disabled.

I recommend using database migrations which are described in the readme. It is the only way to guarantee data integrity when columns change.

**Comment by hacke2** [comment]
OK,Thanks
