### ISSUE TITLE
datastoreType not used?

### ISSUE THREAD

**Issue by ironside** [dresende/node-orm2#670]
From what I can tell, the *datastoreType* function is never used by this library. Searching the entire repo it seems the string _datastoreType_ only appears in these tests.

This property is set in the example (from the integration tests) 

```
db.defineType('numberArray', {
				datastoreType: function(prop) {
					return 'TEXT'
				},
				...
			});
```

**Comment by dxg** [comment]
It's used by a dependency: [sql-ddl-sync](https://github.com/dresende/node-sql-ddl-sync).
