### ISSUE TITLE
Cache being on by default breaks distributed systems

### ISSUE THREAD

**Issue by gileze33** [dresende/node-orm2#672]
Having cache default to true for entities seems a bit silly to me when they only work when you only have one instance of your app running. 

For beginners, this can cause pretty big issues as it's hard to track down why changes in one instance of your application don't get reflected across others..

**Comment by dxg** [comment]
+1
Anyone against disabling it by default and bumping version to 2.2? @dresende?

**Comment by dresende** [comment]
LGTM
