### ISSUE TITLE
Explanation for the Models setup

### ISSUE THREAD

**Issue by lvanbuiten** [dresende/node-orm2#689]
Can anyone answer me the following Stackoverflow question?: http://stackoverflow.com/questions/34406503/why-is-the-order-in-the-setup-so-hard

**Comment by dxg** [comment]
What did you change in the example app? Or is the example app broken?

**Comment by lvanbuiten** [comment]
I basicly took the example project as based and created my own api off it. It is not that spectaculaire, but i was wondering why the order of the setup rules made so much difference. My permission object acts like an user object if the require('./user'), in the models/index.js is called first. 

I will take an look tomorrow if it makes any difference in the example project (Anontxt).

**Comment by lvanbuiten** [comment]
robertklep solved it for me ;)
