### ISSUE TITLE
Timezone option for 'date' types

### ISSUE THREAD

**Issue by pito-svk** [dresende/node-orm2#690]
I have table with 3 columns of datetime type, first is timestamp (datetime WITH time zone), the other two are datetimes WITHOUT time zone.

Is there any way to specify timezone for specific columns?

Like: 

```
timestamp: {
   type: 'date',
   time: true,
   required: true,
   timezone: true
}
```

Thanks.

**Comment by dxg** [comment]
This isn't supported natively, however it may be possible with the use of [custom types](https://github.com/dresende/node-orm2/wiki/Model-Properties#custom-types).

Given that the native `Date` does not have arbitrary timezone support, you'd have to pair this with something like [moment-timezone](http://momentjs.com/timezone/).

If all you want is absolute time, it's highly recommended to store & use UTC time on all your servers.

**Comment by pito-svk** [comment]
Thanks. Will update these fields manually in database.
