### ISSUE TITLE
Query condition objects

### ISSUE THREAD

**Issue by nickythorne** [dresende/node-orm2#702]
Hello,

Reading through the documentation, I'm interested in the custom conditions you can supply to the find object. The documentation mentions the `orm.lt`, `orm.gte` helper functions in order to generate the appropriate conditions.

Would it be possible to compose these conditions directly within the condition object itself? For example:

    {
        "age" : {
           "gt" : 20 
        }
    }

Or do I have to manually construct the object to achieve this?

Thanks.

**Comment by dxg** [comment]
Manually.

**Comment by nickythorne** [comment]
Ok.. and are these conditions supported for all data sources, or just SQL?
