### ISSUE TITLE
Table modifcation

### ISSUE THREAD

**Issue by jorawarsingh** [dresende/node-orm2#703]
hi first of all nice jobb, one question what about table modification? Are you working on that?

**Comment by dxg** [comment]
Do you mean `.sync` to add columns etc for existing tables?
There was some work done on this, however it turned out not to be supported on some database engines and so currently it is disabled in the code.
I recommend using migrations instead; search for "migrations" in the readme.

**Comment by jorawarsingh** [comment]
yes but even changing names of colmns and  types.

**Comment by dxg** [comment]
Migrations can do that.
