### ISSUE TITLE
Do .find() conditions support querying embedded json documents?

### ISSUE THREAD

**Issue by nickythorne** [dresende/node-orm2#704]
Is it possible to query embedded documents via the conditions object?

i.e 

Example Table:

	db.define('document', {
		type : { type : 'text', required: true },
		data : { type : 'object', defaultValue : {} },
	});

Example Record:

	{
		"type" : "USER",
		"data" : {
			"name" : "john doe"
			"age" : 20
		}
	}

Example Query to target inner `data` document:

    var orm = require('orm');
	db.find({ "data.age" : orm.between(16, 30) }, function(error, data) {
	
		// returns matched john doe record
	
	});

**Comment by dxg** [comment]
No, they do not, however you can use `execQuery` to do this manually if you're using Postgres.
