### ISSUE TITLE
sql update and object update

### ISSUE THREAD

**Issue by tcwyjno1** [dresende/node-orm2#721]
When I update a mysql data column.
I use two ways.
1. I use sql like 'update user set email = 'xxx' where id = 1'
In this way, I found the sql running success and returned success.Then the UI refresh and the table showed nothing changed.But the data in database changed successd.I refresh my UI many times
and try to print the object that I searched in server side.I found the data was old too!.Only I restart the serve then my UI table will show the right data which I changed use the sql.

2.I use id to get the user object and use orm2's save method to update.It also update the database column successed and the UI refreshed rihgt! 

Does anyone know why?  It's not a UI cookie issue as the 2nd way to update can success refresh database and UI table

**Comment by dxg** [comment]
Please set `cache: false`. See [here](https://github.com/dresende/node-orm2/wiki/Settings).
