### ISSUE TITLE
Batch create

### ISSUE THREAD

**Issue by olee** [dresende/node-orm2#736]
Hi, is there a way to create multiple entities at once other than using raw queries?
I'm writing a software that often needs to create a lot of entities of the same time and would like to improve it's performance.

**Comment by dxg** [comment]
Pass an array to create fn

**Comment by olee** [comment]
This works?? It's documented nowhere! :sweat_smile: 
This is definitely something that should be added to the wiki!

I'm also working on better Typescript typings for this library so I will add this, too.
OT: I also managed to implement a Typescript annotation based entity model definition framework which got quite powerful and is very easy to use. I'm thinking of publishing that as well when I have some time.
