### ISSUE TITLE
Not working on windows 7

### ISSUE THREAD

**Issue by shakti03** [dresende/node-orm2#737]
getting following error when running on windows 7 

`````` events.js:141
      throw er; // Unhandled 'error' event
      ^
 ORMError: Connection lost - driver does not support reconnection
    at ORM.<anonymous> (C:\Users\dell\Desktop\serialport1\node_modules\orm\lib\ORM.js
:172:31)
    at emitOne (events.js:77:13)
    at Database.emit (events.js:169:7)```
``````

**Comment by zhengxiansen** [comment]
window 10 +1

**Comment by dxg** [comment]
Which driver are you using? Package version & name.

**Comment by zhengxiansen** [comment]
* **Library Version:**
3.2.3


* **Operating System:**
Windows 10

* **Node Version:**
7.2.1

* **NPM Version:**
4.0.3

* **Language:**
ESNext

* **DB:**
“sqlite”

**Comment by dxg** [comment]
Which version of sqlite are you using? Or does the problem affect all versions?

**Comment by Tonyhark** [comment]
throw er; // Unhandled 'error' event
      ^
 ORMError: Connection lost - driver does not support reconnection
    at ORM.<anonymous> (C:\Users\dell\Desktop\serialport1\node_modules\orm\lib\ORM.js
:172:31)
    at emitOne (events.js:77:13)
    at Database.emit (events.js:169:7)```

windows 10 +1 

npm 3.10.10
node 6.10.0
sqlite 3.1.8
orm 3.2.3

**Comment by Tonyhark** [comment]
My problem has been resolved.
Windows has not "/tmp" directory, so create connection failed.
I think it can help most people who encounter the issue.
Perhaps, this issue can be closed.
