### ISSUE TITLE
Instance.save() problem

### ISSUE THREAD

**Issue by onweer** [dresende/node-orm2#740]
Use Instance.save(Object,Function) problem :

console.log(user) => { GETTER/SETTER }
typeof cb => function
console.log(param.phone) => 12321321321

My Code:
return user.save({phone: params.phone}, cb(null, user, 'modify success'));

throw Error: Unknown parameter type 'undefined' in Instance.save() 
at Object.Instance.Object.defineProperty.value (node_modules/orm/lib/Instance.js:603:20)

Problem: 
cb is a function why not use in there ?

If i user this code can sucess:
return user.save({phone: params.phone}, function() { cb(null, user, 'modify success') } );

**Comment by dxg** [comment]
Is this what you're after?
```js
return user.save({ phone: params.phone }, function (err, user) {
  cb(null, user, 'modify success');
})
```
