### ISSUE TITLE
Close connection to ORM

### ISSUE THREAD

**Issue by Tuan-T-Nguyen** [dresende/node-orm2#745]
How can I close connection to database?

**Comment by dxg** [comment]
`.db.close()`

**Comment by abduncan** [comment]
Does this need to be done at the end of every request (I'm thinking express)? Is there a way to have it done without using the Middleware? I prefer to have my repositories abstracted away from the requests.

**Comment by dxg** [comment]
ORM2 uses a connection pool in most scenarios which exists inside the mysql/postgres driver, so no, you shouldn't close connections manually after each request, or ever really.
