### ISSUE TITLE
.save() does not seem to work with type "object"

### ISSUE THREAD

**Issue by xorbis** [dresende/node-orm2#767]
I have a model with a `data` column set to type "object" type and when I call any of those:
```
row.data[idx] = "Hello World!";
row.save(cb);
```
```
let data = row.data;
data[idx] = "Hello World!";
row.save({data: data}, cb);
```
No UPDATE call shows up in the debug log.

I had to use a raw query to achieve a single row update.
Any clue on what I might be doing wrong?
This is a simple model with no relations.
All options are on defaults except for debug.

**Comment by dxg** [comment]
It's a result of dirty tracking; as far as ORM is concerned, the object hasn't changed, so no update is run.
Have a look at #517 .

You can solve this by calling:
```
row.set(['data', idx], "Hello World!")
```
I believe.. but see #517 for more.

**Comment by xorbis** [comment]
Thanks much!
