### ISSUE TITLE
Find operators documentation

### ISSUE THREAD

**Issue by xorbis** [dresende/node-orm2#770]
Trying to use the find operators like so:

```
contacts.find({
	id: { ">": 1000 }
});

```
Getting this:

```
... FROM `contacts` WHERE `id` = `>` = 1000
```

How are we supposed to use the find operators on fields, the doc is lacking some example.

**Comment by dxg** [comment]
https://github.com/dresende/node-orm2#conditions
If doco is missing, please add it.

**Comment by xorbis** [comment]
Got confused by this doc:
https://media.readthedocs.org/pdf/node-orm/latest/node-orm.pdf
Section 1.2.1

Sorry! thanks for pointing me in the right direction.
