### ISSUE TITLE
Changing unique ID column name error... (PostgreSQL 9.6.1)

### ISSUE THREAD

**Issue by cwgabel** [dresende/node-orm2#771]
**Advanced Options  (from wiki)**
```javascript
var Person = db.define("person", {
    name : String
}, {
    id   : "person_id"
});
```
Cannot get this to work (from example, with added modification):

```javascript
module.exports = function(orm, db) {
    var Message = db.define('message', {
        title: { type: 'text', required: true },
        body: { type: 'text', required: true, big: true },
        createdAt: { type: 'date', required: true, time: true }
    }, {
        **id: "message_id",**
        hooks: {
        ...
```

Error message: 

 **throw new ORMError("Model defined without any keys", 'BAD_MODEL', { model: opts.table });**

  This works just fine:
```javascript
       db.settings.set("properties.primary_key", "message_id");  
 ```

Thank you for any help you can provide.

**Comment by cwgabel** [comment]
Not from wiki, but from [http://dresende.github.io/node-orm2/](http://dresende.github.io/node-orm2/l)

**Comment by dxg** [comment]
Try `key: true` as seen here: https://github.com/dresende/node-orm2#advanced-options

**Comment by cwgabel** [comment]
[http://dresende.github.io/node-orm2/](http://dresende.github.io/node-orm2/) does not have any mention of this usage:

 ` personId : { type: 'serial', key: true },` 

which is where I thought documentation resides (given how nice it looks). 

So the wiki is the ultimate destination of all node-orm2 documentation?

**Comment by dxg** [comment]
Hey @dresende can we remove those docs somehow? Or point them to the main readme?

**Comment by dresende** [comment]
Done, dropped gh-pages branch ;)
