### ISSUE TITLE
How to update fields in joining table

### ISSUE THREAD

**Issue by akshaykumar12527** [dresende/node-orm2#774]
I am using Node-orm2 with MySql. All things are working fine but I am looking for an ORM feature through which I can update fields of joining table. Is there any function available? Or I need to use raw query?

Thanks.

**Comment by dresende** [comment]
Please read [Model.hasMany](https://github.com/dresende/node-orm2/wiki/hasMany) and check back again if you have any doubts.

**Comment by lawrencebensaid** [comment]
Either I am missing something or this issue has not been answered. Can we get a response on this please?
