### ISSUE TITLE
Double calling callback in db.load

### ISSUE THREAD

**Issue by antishov** [dresende/node-orm2#778]
~~~
const argumentsList = modelsNamesList.map(modelName => `${__dirname}/models/${modelName}`);
argumentsList.push(callback);
db.load(...argumentsList);
~~~

In this example callback for the last item in array will be called two times: when model was loaded and when "files" variable will be empty. Error in file ORM.js, line 278

**Comment by dxg** [comment]
Can you please provide a fully functioning sample?
Along the lines of https://github.com/dresende/node-orm2/issues/326#issuecomment-49588445

**Comment by antishov** [comment]
I can't reproduce error now, sorry
