### ISSUE TITLE
Unicode in query is improperly escaped 

### ISSUE THREAD

**Issue by jacgrady1** [dresende/node-orm2#784]
```
const updateQuery = 'UPDATE table1 SET state = ?  where id = 1';
const state = 'abc\u008Fdef';
db.drive.execQuery(updateQuery, [state], (err, data) => {
});
```
orm truncate the state from the unicode escape sequence, after executing the query,  
`state = 'abc';`

**Comment by dresende** [comment]
I found nodejs does not properly handle emojis properly (or didn't, I don't know the latest version). A year ago I wrote this:

```js
function encode_emojis(s) {
	return s.replace(/[\u007f-\uffff]/g, (c) => ('\\u'+('0000'+c.charCodeAt(0).toString(16)).slice(-4)));
};
```

Try it before passing the string to orm.

**Comment by dxg** [comment]
https://stackoverflow.com/questions/60827366/node-js-emoji-in-utf8-request-returning-characters may help

**Comment by lawrencebensaid** [comment]
@dxg How would I apply this charset option in orm2?

**Comment by dxg** [comment]
@lawrencebensaid add `?charset=utf8mb4` to your connection string or `query: { charset: utf8mb4' }` to your connection object.

I've [added a test](https://github.com/dresende/node-orm2/commit/8a0e8ac5799228c16cfefde4a69a0438e6042726) for this as well as examples in the doco.
