### ISSUE TITLE
Adding a column to a table?

### ISSUE THREAD

**Issue by napindc** [dresende/node-orm2#823]
Is there a way to add a column to an existing table? I changed the model on an existing table to add a new column, and I called the `sync()` method on the model, but it didn't add it.

**Comment by dxg** [comment]
Have a look at the `Migrations` link here: https://github.com/dresende/node-orm2#features
Beyond that, there is no "automated" way. Someone started work on that once, but it was never finished.

**Comment by huuthang1993** [comment]
sad, so sync is useless in prod because we can't drop the table with data to re-create
