### ISSUE TITLE
Pool connection with postgres

### ISSUE THREAD

**Issue by viico** [dresende/node-orm2#825]
Hello,

I tried node-orm2 for the first time today. I think there is an issue on pool connection with pg driver from v7.0.

With newer version I have "TypeError: this.db.connect is not a function" error when trying to connect using pool connection. No error with "query: {pool: false}" option.

I downgraded pg driver version to 6.4.1 and it fixed the issue. But there is warning at connect: "DeprecationWarning: PG.connect is deprecated - please see the upgrade guide at https://node-postgres.com/guides/upgrading". The link explain how to resolve the connect issue.

I'll continue to discover your tools.

**Comment by dxg** [comment]
Yeah someone needs to add support for PG driver versions >= 7.0.

**Comment by dxg** [comment]
Seems I resolved this a while ago but forgot to mention that here.
https://github.com/dresende/node-orm2/blob/master/Changelog.md#v500
