### ISSUE TITLE
Bad integration with EJS

### ISSUE THREAD

**Issue by GhoSTBG** [dresende/node-orm2#827]
First of all I'm newbie in NodeJS and maybe my issue would be kinda useless.
So firstly, I have 2 models with one to many relationship and it's working fine, but the problem is that the getModel function is async and I cannot display it in the EJS is there any way to get through this without writing async code?
Another thing that I can't understand is: how can I convert my getter;setter class to JSON Object because I want to get all the data and create a form with dropdowns using the data in MySQL.

Best Regards,
GhoSTBG

**Comment by dxg** [comment]
1. Ideally you should not be calling async functions or database model functions inside your view - it would be better to have a function somewhere before this step which obtains all necessary data.
2. ORM model instances behave like JSON objects:
```js
console.log(modelInstance)
// prints weird get/set stuff
console.log(JSON.stringify(modelInstance, null, 2))
// prints the actual data
```
The console thing makes it look confusing, but it behaves like a JSON object, so it should just work.

**Comment by GhoSTBG** [comment]
@dxg I really can't get this working. Here's my code:

```
let devices = [];
req.models.cluster.all(function(err, clusters) {
  clusters.forEach((cluster) => {
    cluster.getDevices((err, device) => {
      devices.push(JSON.stringify(device));
    })
    console.log(devices);
  });
});
```

console.log(devices) returns []

**Comment by dxg** [comment]
@GhoSTBG it's because `cluster.getDevices` is asynchronous and will return some time later. The `console.log` is printing before the call completes.

I recommend using a package like https://www.npmjs.com/package/async as then you can change the code to:

```js

const async = require('async');

let devices = [];

req.models.cluster.all(function(err, clusters) {
  async.map(clusters, function (item, cb) {
  	item.getDevices(cb);
  }, function (err, devices) {
  	if (err) throw err;

  	console.log(JSON.stringify(devices, null, 2));
  });
});
```
