### ISSUE TITLE
groupBy is not working with findAsync

### ISSUE THREAD

**Issue by stardev24** [dresende/node-orm2#835]
Hi,

As per the documentation  Filtering and sorting section I have tried 
Person.findAsync({status:'active',form:'success'}, {groupBy:'permission'})
  .then(function(results) {
    console.log(results);
  });
But its not at all considering groupBy.I am using postgresql as my database.

**Comment by dxg** [comment]
I think the example was incorrect. I don't think such a feature is supported.
Actually the Promise documentation was a mess - it was duplicating all other documentation.

I've cleaned it up: https://github.com/dresende/node-orm2#promise-support
