### ISSUE TITLE
ORM Support for MySQL v8.x

### ISSUE THREAD

**Issue by RHieger** [dresende/node-orm2#843]
If this is a duplicate issue,  I apologize in advance. I am working with a team of students right now building an Angular/NodeJS/Express/MySQL-based web application, and have run into the problem that the ORM we were using does not support MySQL v8.x.

I was browsing your documentation and could not find **node-orm2** supports MySQL v8.x. Specifically, the problem is that in our current ORM (**Sequelize**), the new SSH-based authentication model is not recognized.

Does **node-orm2** fully support this model? If not, are there any workarounds?

Any enlightenment you can provide on this would be greatly appreciated.

Thanks.

**Comment by dxg** [comment]
Hi - posting this answer for anyone else with the same question;
No - no work has been undertaken to specifically support MySQL v8.
